<h1>numpy</h1>

numpy is a linear algebra library for python and 
almost all the libraries in the pydata ecosystem rely on numpy as on of their basic building blocks
numpy is incredibly fast and has its bindings to c libraries

In [3]:
import numpy as np

<h3>1. Casting a normal python list into an array</h3>

In [4]:
lst = [2,5,8,3,9,6]
print(lst)
print(type(lst))

[2, 5, 8, 3, 9, 6]
<class 'list'>


In [6]:
arr = np.array(lst)
print(arr)
print(type(arr))

[2 5 8 3 9 6]
<class 'numpy.ndarray'>


<h4>2D arrays</h4>

In [70]:
lst_2d = [[2,6,4],[5,8,1,],[3,7,6]]
print(lst_2d)
print(type(lst_2d))

[[2, 6, 4], [5, 8, 1], [3, 7, 6]]
<class 'list'>


In [71]:
arr_2d = np.array(lst_2d)
print(arr_2d)
print(type(arr_2d))

[[2 6 4]
 [5 8 1]
 [3 7 6]]
<class 'numpy.ndarray'>


<h3>2. Creating numpy arrays</h3>

<h4>2.1 arange() </h4>
It can be used to create a consequtively increasing array of integers

np.arange(lower_limit, upper_limit, stepping_value)

In [13]:
np.arange(10,18,2)             # lower limit is inclusive and upper limit is exclusive

array([10, 12, 14, 16])

<h4>2.2 a null matrix of any size can be made using the np.zero() function using ones() and zeros() functions</h4>

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((3,5))           # to create a 2-dimensional array the tuple (rows, columns) is to be passed as the arguement

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

<h5>2.3 Same thing can be done to create a matrix with all entries as one</h5>

In [24]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

<h5>2.4 using eye() function an identity matrix can be made of specified length</h5>

In [27]:
np.eye(4)                  # a single arguement gives a square matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [95]:
np.eye(3,5)                #two arguements can be provided to create a 2-dimensional identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

<h4>2.3 linspace()</h4>
Can be used to bound the entries between a given limit despite extracting any number of entries

In [23]:
np.linspace(1,5,7)            # we get total 7 outputs

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

<h4>2.4 selecting entries between 0 and 1 using rand() and randn() functions</h4>

In [32]:
np.random.rand(4,4)           #gives only positive entries

array([[0.07230463, 0.79686206, 0.12191939, 0.28432191],
       [0.64198904, 0.08088477, 0.98981487, 0.40377731],
       [0.66115606, 0.43366772, 0.54670267, 0.2048777 ],
       [0.12519376, 0.90964707, 0.16158446, 0.46730992]])

In [44]:
np.random.randn(3,3)         # gives positive as well as negative entries

array([[-0.79367384, -0.94724569,  0.18420125],
       [-0.11341627,  0.83062439, -0.6014296 ],
       [ 0.52754863, -0.36195493, -0.27987289]])

In [41]:
arr1 = np.array([2,4,67,2,4,6,45,23,5,634,2,5,7.98,67,34,54])
print(len(arr1))

16


<h4>2.5 reshape()</h4>
the product of two arguements must equal the length of array on which the reshape function is used

In [49]:
arr2 = arr1.reshape(4,4)
print(arr2)             # 4*4 = 16 = len(arr1)

[[  2.     4.    67.     2.  ]
 [  4.     6.    45.    23.  ]
 [  5.   634.     2.     5.  ]
 [  7.98  67.    34.    54.  ]]


In [113]:
arr2_2D = np.arange(50).reshape(5,10)
print(arr2_2D)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


<h4>2.6 Finding maximum and minimum value of any array</h4>
These functions doesn't apply on 2-dimensional arrays

In [55]:
print(max(arr1))
print(min(arr1))
print(arr1.argmax())
print(arr1.argmin())                      

634.0
2.0
9
0


<h4>2.7 randint()</h4>

In [11]:
arr3 = np.random.randint(1,20,25)             #doesn't include the upper limit (20 in this case)
print(arr3)
print(arr3.dtype)                             #to pirnt the actual datatype of the terms in array we use dtype

[ 3  3 10  9 12  7  7 15  5 18 13 13  5  1  7 13  8  3 17 15 14 17 10 16
  1]
int64


<h3>3. Slicing of arrays</h3>
its exactly same as the slicing of list

In [56]:
arr4 = np.array([4,7,2,9,5,6,10])
print(arr4[0:len(arr4)])                       #prints all the values of the array
print(arr4[1:8])                               #prints value starting from index 1 upto index 7(excluding arr[8])
print(arr4[:6])                                #if nothing spsecified at left of colon it starts from the first element
print(arr4[:])                                 #if nothing specified at the right thrn it prints upto last element

[ 4  7  2  9  5  6 10]
[ 7  2  9  5  6 10]
[4 7 2 9 5 6]
[ 4  7  2  9  5  6 10]


but if any change is made in any slice of the array, it affects the original array

In [51]:
array_slice = arr4[1:4]
print(array_slice)
array_slice[:] = 222
print(arr4)

[222 222 222]
[  4 222 222 222   5   6  10]


to do something like that we need to make a fresh copy of the slice

In [72]:
array_slice2 = arr4[1:4].copy()               #this makes a fresh copy of that slice of the array
array_slice2[:] = 888
print(array_slice2)
print(arr4)                                   #this doesn't affect teh parent array

[888 888 888]
[ 4  7  2  9  5  6 10]


<h4>slicing might can also be done in 2-dimensional array</h4>

In [82]:
a = np.array([[12,43,32,21,24], [38,24,6,67,85],[32,76,86,13,54],[23,45,92,18,28],[10,20,64,59,13]])
a

array([[12, 43, 32, 21, 24],
       [38, 24,  6, 67, 85],
       [32, 76, 86, 13, 54],
       [23, 45, 92, 18, 28],
       [10, 20, 64, 59, 13]])

In [89]:
print(a[2,4])                                   #it will access any element of the 2d array -- a[row_index, column_index]
print(a[2][4])                                  #prints same as a[2,4]
print(a[1:3,2:4])                               #a slice of rows or column may also be passed

54
54
[[ 6 67]
 [86 13]]


<h3>4. Boolean array</h3>
we can create a boolean array by comparing each element with a value

In [108]:
a1 = np.random.randint(1,10,9)
a1

array([6, 8, 6, 3, 9, 8, 1, 1, 6])

In [114]:
print(a1)
a2 = a1 > 6                                     #this is a boolean array 
print(a2)                                       
print(a1[a2])                                   #this will print the values which are greater than 6 in the array a1

[6 8 6 3 9 8 1 1 6]
[False  True False False  True  True False False False]
[8 9 8]


all the mathematical operations can be done on the matrices and also matrix and scalar