In [1]:
import numpy as np

In [9]:
def ones_square(x):
    arr = np.ones((x,x))
    arr[1:-1,1:-1] = 0
    print(arr)
a = int(input('enter the number'))
ones_square(a)

enter the number8
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
